runtime: python312  # replace with your Python version
entrypoint: gunicorn -b :$PORT app:app  # replace 'main:app' with your app's entry point

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
  secure: always


# set GOOGLE_APPLICATION_CREDENTIALS=/static/SciWeb_API_secret.json